create table purchase
(
    id          integer generated by default as identity,
    purchase_id varchar(255),
    order_id    varchar(255),
    supplier_id varchar(255),
    supplier_name varchar(255),
    status      integer,
    datetime    timestamp with time zone,
    updated    timestamp with time zone,
    supplier_order_id varchar(255),
    primary key (id)
);
create table order_line
(
    id          integer generated by default as identity,
    purchase_id integer,
    quantity    integer,
    product_id  varchar(255),
    name       varchar(255),
    price      numeric,
    category   integer,
    primary key (id)
);
ALTER TABLE order_line
    ADD FOREIGN KEY (purchase_id)
        REFERENCES purchase (id);